---
driver:
  name: docker
  binary: <%= `which docker` %>
  use_sudo: false
  socker: <%= ENV['DOCKER_HOST'] %>
busser:
  sudo: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  files_path: test/shared

platforms:
  - name: ubuntu-logstash-tgz
    driver_config:
      image: ubuntu:12.04
      use_cache: true
      dockerfile: docker/ubuntu12.04-dockerfile
    provisioner:
      custom_facts:
        logstash_package: http://download.elastic.co/logstash/logstash/logstash-1.5.0.tar.gz 

suites:
  - name: logstash-cli
  - name: logstash-config
