---
driver:
  name: docker
  binary: /usr/bin/docker
  use_sudo: false
busser:
  sudo: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  files_path: test/shared

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:12.04
      use_cache: true
      dockerfile: docker/ubuntu12.04-dockerfile

suites:
  - name: logstash-cli
  - name: logstash-config
